version: '3.10'

services:
  api:
    image: ml-practice:api
    volumes:
      - ./src:/project/src
      - ./models:/project/models
      - ./.docker.env:/project/.env
    build:
      context: ./
      dockerfile: api/Dockerfile
    restart: always
    command: sh -c "uvicorn src.main:app --reload --host=api --port=8000"

  rabbit:
    image: ml-practice:rabbitmq
    build:
      context: ./rabbit_mq
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5674:5672"
      - "15674:15672"

  celery:
    image: ml-practice:celery
    restart: always
    build:
      context: .
      dockerfile: ./celery_app/Dockerfile
    volumes:
      - ./src:/project/src
      - ./models:/project/models
      - ./.docker.env:/project/.env
    stdin_open: true
    #  tty: true
    #  network_mode: host # use it only with linux
    ports:
      - "1024-1070:1024-1070"
    command: >
      sh -c """
        celery -A src.celery_application.celery beat &
        celery -A src.celery_application.celery worker -E -Q cold_start_q,health_check_q,default_q -c 2
      """
    depends_on:
      - rabbit
      - postgres

  postgres:
    image: ml-practice:postgres
    restart: always
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
      network: host
    ports:
      - "5433:5433"
    environment:
      - PGPORT=5433
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  dash:
    image: ml-practice:dash
    restart: always
    build:
      context: .
      dockerfile: ./dash_app/Dockerfile
    ports:
      - "8050:8050"
    command: sh -c "python /project/src/dashboards/dashboards.py"

  nav-app:
    image: ml-practice:dash
    restart: always
    build:
      context: .
      dockerfile: ./dash_app/Dockerfile
    command: sh -c "python /project/src/dashboards/navigation_app/app.py"

  gateway:
    image: ml-practice:gw
    restart: always
    build:
      context: ./gateway
      dockerfile: ./Dockerfile
    ports:
      - "8002:80"
    depends_on:
      - api
      - nav-app
      - celery
